---
title: "soil-type-methane-flux"
author: "Judy-Malas"
date: "3/7/2022"
output: html_document
---
 
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r load packages}

library(tidyverse)
library(ggplot2)
library(readxl)

```

```{r import-data}


soil_profile_data <- read_excel("Data/ISCN_SOC-DATA_PROFILE_1-1 2.xlsx")




```

```{r soil profile structure}

str(soil_profile_data)


```

```{r exploratory plot1}

ggplot(soil_profile_data, aes(soil_taxon)) +
  geom_bar()

```

```{r}
c2 <- read_csv("data/ISCN-c2.csv") %>% 
    janitor::clean_names()

```

```{r str}

str(c2)

```

```{r}

c2 %>% 
  select(clay_tot_psa_percent) %>% 
  filter()

```

```{r}

clay <- drop_na(c2, clay_tot_psa_percent)

ggplot(clay, aes(clay_tot_psa_percent))+
  geom_histogram() +
  labs(x = "Clay %")+
  theme_bw()

```

```{r}

ggplot(clay, aes(state_state_province)) +
  geom_bar()

```

```{r}
clay %>% 
  count(state_state_province) %>% 
  arrange(desc(n))
```

```{r }

range(clay$lat_dec_deg)
range(clay$long_dec_deg)


```


```{r}
colnames(clay)


```

```{r clay-v-soc}

clay_rmout <- clay %>% 
  filter(soc_g_cm_2 < 60)

ggplot(clay_rmout, aes(clay_tot_psa_percent, soc_g_cm_2)) +
  geom_point() + 
  theme_bw() +
  labs(y = "SOC g/cm2", x = "Clay %")

```


```{r install-cosore}
devtools::install_github("bpbond/cosore")
```

```{r}

library(cosore)

citation("cosore")

db_info <- csr_database()
tibble::glimpse(db_info)

```

37.50042 40.50000


```{r}
db_info %>% 
  filter(CSR_LATITUDE > 37.5, 
         CSR_LATITUDE < 40.51, 
         CSR_LONGITUDE > -129.6, 
         CSR_LONGITUDE < 141.51)

# 13 datasets
```

